name: Gerar APK Android

# Isso permite que você aperte um botão para rodar o robô quando quiser
on:
  workflow_dispatch: 

jobs:
  build-android:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v3

      - name: 🟢 Preparar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ☕ Preparar o Java (Android Studio)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 📦 Instalar dependências do projeto
        run: npm install

      - name: 🏗️ Construir o aplicativo Web (React)
        run: npm run build

      - name: 📱 Converter para Android (Capacitor)
        run: |
          npx cap add android || true
          npx cap sync android

      - name: ⚙️ Gerar o arquivo .APK
        working-directory: ./android
        run: bash ./gradlew assembleDebug

      - name: 🚀 Entregar o APK pronto
        uses: actions/upload-artifact@v3
        with:
          name: GabaritoPro-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
